### ISSUE TITLE
go_ca_signing_file.write(signing_policy) TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by griznog** [globus/globus-toolkit#128]
Hi,

After upgrading to 

```
globus-connect-server-4.0.55-1.el7+gt6.noarch
globus-connect-server-common-4.0.55-1.el7+gt6.noarch
```
I'm getting the following error running `globus-connect-server-setup -v --force`:

```
ENTER: GCMU.configure_trust_roots()
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/globus/connect/server/setup.py", line 131, in main
ioobj.setup(reset=reset)
File "/usr/lib/python3.4/site-packages/globus/connect/server/io/__init__.py", line 72, in setup
self.configure_trust_roots(**kwargs)
File "/usr/lib/python3.4/site-packages/globus/connect/server/io/__init__.py", line 307, in configure_trust_roots
super(IO, self).configure_trust_roots(**kwargs)
File "/usr/lib/python3.4/site-packages/globus/connect/server/__init__.py", line 447, in configure_trust_roots
go_transfer_ca_2_signing_policy)
File "/usr/lib/python3.4/site-packages/globus/connect/security/__init__.py", line 128, in install_ca
install_signing_policy(ca_signing_policy, cadir, ca_hash)
File "/usr/lib/python3.4/site-packages/globus/connect/security/__init__.py", line 48, in install_signing_policy
go_ca_signing_file.write(signing_policy)
TypeError: must be str, not bytes
Using MyProxy server on None
```

If I change `/usr/lib/python3.4/site-packages/globus/connect/security/__init__.py`, line 48 from

```go_ca_signing_file.write(signing_policy)```

to

```go_ca_signing_file.write(str(signing_policy))```

That seems to make it happy. Is there a better way to fix this?

Best,

griznog

**Comment by griznog** [comment]
My issue is probably fixed in https://github.com/globus/globus-connect-server/commit/3fc67969bc4caf643d08783ccac4877c44777be3.
