### ISSUE TITLE
`gss_init_sec_context` is not thread safe

### ISSUE THREAD

**Issue by paulmillar** [globus/globus-toolkit#48]
Calls to `gss_init_sec_context` are not thread safe, even when threads do not share any of the memory associated with any argument: arguments are either allocated off the stack or from heap in structures to which only a single thread has access.

A simple work-around is available: by adding a mutex to protect against concurrent access the application no longer crashes.  Here is the corresponding code fragment, with mutex work-around:

```
            pthread_mutex_lock(&globus_gss);
            major_status = gss_init_sec_context(&minor_status,
                                                data->credential_handle,
                                                &data->context_handle,
                                                target_name,
                                                oid,
                                                data->context_flags,
                                                0,
                                                NULL,   /* no channel bindings */
                                                &recv_tok,
                                                NULL,   /* ignore mech type */
                                                &send_tok,
                                                &ret_flags,
                                                NULL);  /* ignore time_rec */
            pthread_mutex_unlock(&globus_gss);
```

**Comment by paulmillar** [comment]
Here's a typical back-trace from one of these crashes:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5246f1c in globus_gsi_callback_handshake_callback () from /usr/lib/x86_64-linux-gnu/libglobus_gsi_callback.so.0
(gdb) bt
#0  0x00007ffff5246f1c in globus_gsi_callback_handshake_callback () from /usr/lib/x86_64-linux-gnu/libglobus_gsi_callback.so.0
#1  0x00007ffff59f080b in internal_verify (ctx=0x7fffffffa720) at x509_vfy.c:1689
#2  0x00007ffff59f134b in X509_verify_cert (ctx=0x7fffffffa720) at x509_vfy.c:368
#3  0x00007ffff5244f97 in globus_gsi_callback_X509_verify_cert () from /usr/lib/x86_64-linux-gnu/libglobus_gsi_callback.so.0
#4  0x00007ffff4bfe1ee in ssl_verify_cert_chain (s=s@entry=0x876210, sk=sk@entry=0x874f60) at ssl_cert.c:518
#5  0x00007ffff4bdb313 in ssl3_get_server_certificate (s=s@entry=0x876210) at s3_clnt.c:1153
#6  0x00007ffff4bdfa94 in ssl3_connect (s=0x876210) at s3_clnt.c:324
#7  0x00007ffff4be8ab0 in ssl23_get_server_hello (s=<optimized out>) at s23_clnt.c:805
#8  ssl23_connect (s=0x876210) at s23_clnt.c:228
#9  0x00007ffff4c0783c in ssl_ctrl (b=0x8766b0, cmd=<optimized out>, num=<optimized out>, ptr=<optimized out>) at bio_ssl.c:423
#10 0x00007ffff730914a in globus_i_gsi_gss_handshake (minor_status=0x7fffffffab34, context_handle=0x876890) at globus_i_gsi_gss_utils.c:925
#11 0x00007ffff7304f70 in gss_init_sec_context (minor_status=0x7fffffffac34, initiator_cred_handle=0x0, context_handle_P=0x86a150, target_name=0x9e, mech_type=0x0, req_flags=50, time_req=0, input_chan_bindings=0x0, 
    input_token=0x7fffffffac80, actual_mech_type=0x0, output_token=0x7fffffffac70, ret_flags=0x7fffffffac3c, time_rec=0x0) at init_sec_context.c:182
#12 0x00007ffff751ae18 in ?? () from /usr/lib/libcgsi_plugin_voms_cpp.so.1
#13 0x00007ffff7bca9d7 in ?? () from /usr/lib/x86_64-linux-gnu/libgsoap++.so.5
#14 0x00007ffff7bcab65 in soap_connect_command () from /usr/lib/x86_64-linux-gnu/libgsoap++.so.5
#15 0x000000000058c799 in soap_call_srm__srmPing (soap=0x7ffff7f95010, soap_endpoint=0x866e08 "https://release-2-15.desy.de:8443/srm/managerv2", soap_action=0x5d0263 "srmPing", srmPingRequest=0x7fffffffb6c0, _param_39=...)
    at soapClient.cpp:2058
#16 0x0000000000594bf7 in Ping (soap=0x7ffff7f95010, srm_endpoint=0x866e08 "https://release-2-15.desy.de:8443/srm/managerv2", authorizationID=0x0, resp=0x866da0) at Ping.cpp:63
#17 0x0000000000494893 in srmPing::exec (this=0x864a90, proc=0x7fffffffbe50) at n_srmPing.cpp:97
#18 0x000000000040bd61 in Process::exec_with_timeout (this=0x7fffffffbe50) at process.cpp:870
#19 0x000000000040c1e1 in Process::eval_with_timeout (this=0x7fffffffbe50) at process.cpp:979
#20 0x000000000040b83e in Process::eval_sequential_repeats (this=0x7fffffffbe50) at process.cpp:705
#21 0x000000000040adbe in Process::eval_repeats (this=0x7fffffffbe50) at process.cpp:500
#22 0x000000000040a9d7 in Process::eval (this=0x7fffffffbe50) at process.cpp:447
#23 0x000000000040c69b in Process::eval_subtree (this=0x7fffffffc460, root_exec=0) at process.cpp:1046
#24 0x000000000040c565 in Process::eval_with_timeout (this=0x7fffffffc460) at process.cpp:1022
#25 0x000000000040b83e in Process::eval_sequential_repeats (this=0x7fffffffc460) at process.cpp:705
#26 0x000000000040adbe in Process::eval_repeats (this=0x7fffffffc460) at process.cpp:500
#27 0x000000000040a9d7 in Process::eval (this=0x7fffffffc460) at process.cpp:447
#28 0x000000000040b6a6 in Process::eval_par (this=0x862840) at process.cpp:669
#29 0x000000000040ba59 in Process::eval_sequential_repeats (this=0x862840) at process.cpp:778
#30 0x000000000040adbe in Process::eval_repeats (this=0x862840) at process.cpp:500
#31 0x000000000040a9d7 in Process::eval (this=0x862840) at process.cpp:447
#32 0x0000000000407333 in s2_run (argc=10, argv=0x7fffffffcac8, i=10) at s2.cpp:985
#33 0x0000000000407470 in main (argc=10, argv=0x7fffffffcac8) at s2.cpp:1030
(gdb) 
```

**Comment by paulmillar** [comment]
Any progress on answering this issue?
