### ISSUE TITLE
globus-gridftp-server crashes with SIGFPE

### ISSUE THREAD

**Issue by nlmills** [globus/globus-toolkit#77]
Hello, I am trying to run GridFTP over a single port. I set `GLOBUS_TCP_PORT_RANGE=5001,5001` and tried to run a transfer, but the server crashed with a division by zero error. I am running `globus_gridftp_server: 11.1 (1468609031-85)`.

I traced the bug to `globus_xio_tcp_driver.c:1316`:

``` c
 port = min_port + (int)(rand() % (max_port-min_port));
```

In my case `min_port == max_port`. This bug was introduced in commit dee08796a14821e68af1aa2d5226f6a180136507.

Thank you,

Nick Mills
Graduate Research Assistant
Clemson University

```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7703265 in globus_l_xio_tcp_bind (fd=10, addr=0x651590, addr_len=<optimized out>, min_port=5001, max_port=5001, 
    listener=listener@entry=1) at globus_xio_tcp_driver.c:1316
1316    globus_xio_tcp_driver.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7703265 in globus_l_xio_tcp_bind (fd=10, addr=0x651590, addr_len=<optimized out>, min_port=5001, max_port=5001, 
    listener=listener@entry=1) at globus_xio_tcp_driver.c:1316
#1  0x00007ffff7703ada in globus_l_xio_tcp_create_listener (server=0x6582b0, attr=0x6510b0) at globus_xio_tcp_driver.c:1492
#2  globus_l_xio_tcp_server_init (driver_attr=<optimized out>, contact_info=<optimized out>, op=0x660f60)
    at globus_xio_tcp_driver.c:1608
#3  0x00007ffff76e4526 in globus_xio_driver_pass_server_init (op=op@entry=0x660f60, contact_info=contact_info@entry=0x7fffffffdcc0, 
    driver_server=driver_server@entry=0x0) at globus_xio_pass.c:1682
#4  0x00007ffff76de3cf in globus_xio_server_create (server=0x658450, server_attr=0x650090, stack=<optimized out>)
    at globus_xio_server.c:984
#5  0x00007ffff5c3f1cb in ?? () from /usr/lib/x86_64-linux-gnu/libglobus_io.so.3
#6  0x00007ffff68ad397 in globus_ftp_control_local_pasv () from /usr/lib/x86_64-linux-gnu/libglobus_ftp_control.so.1
#7  0x00007ffff7b90a81 in globus_i_gfs_data_request_passive () from /usr/lib/x86_64-linux-gnu/libglobus_gridftp_server.so.6
#8  0x00007ffff7baf79a in ?? () from /usr/lib/x86_64-linux-gnu/libglobus_gridftp_server.so.6
#9  0x00007ffff6acb047 in globus_i_gsc_passive () from /usr/lib/x86_64-linux-gnu/libglobus_gridftp_server_control.so.0
#10 0x00007ffff6ad1f9a in ?? () from /usr/lib/x86_64-linux-gnu/libglobus_gridftp_server_control.so.0
#11 0x00007ffff6ac7e92 in ?? () from /usr/lib/x86_64-linux-gnu/libglobus_gridftp_server_control.so.0
#12 0x00007ffff7937480 in globus_callback_space_poll_nothreads () from /usr/lib/x86_64-linux-gnu/libglobus_common.so.0
#13 0x00007ffff7956698 in ?? () from /usr/lib/x86_64-linux-gnu/libglobus_common.so.0
#14 0x0000000000403883 in main ()
```

**Comment by nlmills** [comment]
Does anyone have an update on this issue? I'm writing up a technical document that may be included in a future research paper, and I'd like to report this issue as "resolved" or "nearly resolved." I'm hoping it will be a quick fix.

**Comment by michaellink** [comment]
Hi Nick.

An fix for this issue should be released next week.

Thanks,
Mike
